[project]
name = "shellblocks"
version = "0.1"
dependencies = [
    "pytest",
    "unicorn>=2.0,<2.1",
]
readme = "README.md"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
